model_name_or_path: allenai/OLMo-2-1124-13B-Instruct
tokenizer_name_or_path: allenai/OLMo-2-1124-13B-Instruct
use_vllm: true
use_slow_tokenizer: false
max_new_tokens: 8192
temperature: 0.0
batch_size: 1
load_in_8bit: false
gptq: false
format: default