model_name_or_path: allenai/tulu-v2.5-ppo-13b-uf-mean-70b-uf-rm
tokenizer_name_or_path: allenai/tulu-v2.5-ppo-13b-uf-mean-70b-uf-rm
use_vllm: true
use_slow_tokenizer: false
max_new_tokens: 8192
temperature: 0.0
batch_size: 1
load_in_8bit: false
gptq: false
format: default