model_name_or_path: TheBloke/koala-7B-HF
tokenizer_name_or_path: TheBloke/koala-7B-HF
use_vllm: true
use_slow_tokenizer: false
max_new_tokens: 8192
temperature: 0.0
batch_size: 1
load_in_8bit: false
gptq: false
format: 'BEGINNING OF CONVERSATION: USER: {prompt} GPT:'