gpt4-turbo_alpacaeval_no_reference:
  prompt_template: "gpt4-turbo_alpacaeval_no_reference/prompt.txt"
  fn_completions: openai_completions
  completions_kwargs:
    max_tokens: 100
    model_name: gpt-4-turbo
    temperature: 0.0
  fn_completion_parser: "ranking_parser"
  batch_size: 1