gpt4-turbo_basic_no_reference_no_ex:
  batch_size: 1
  completion_parser_kwargs:
    matcher:
      A: 1.0
      B: 2.0
      tie: 0.0
  completions_kwargs:
    max_tokens: 100
    model_name: gpt-4-turbo
    temperature: 0.0
  fn_completion_parser: match_parser
  fn_completions: openai_completions
  prompt_template: gpt4-turbo_basic_no_reference_no_ex/prompt.txt
