model_name_or_path: mistralai/Mistral-7B-Instruct-v0.3
tokenizer_name_or_path: mistralai/Mistral-7B-Instruct-v0.3
use_vllm: true
use_slow_tokenizer: false
max_new_tokens: 8192
temperature: 0.0
batch_size: 1
load_in_8bit: false
gptq: false
format: default