model_name_or_path: microsoft/Phi-3-medium-4k-instruct
tokenizer_name_or_path: microsoft/Phi-3-medium-4k-instruct
use_vllm: true
use_slow_tokenizer: false
max_new_tokens: 8192
temperature: 0.0
batch_size: 1
load_in_8bit: false
gptq: false
format: default